// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221210803_AddingSpots")]
    partial class AddingSpots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Abstracts.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("SpotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("SpotId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("SpotNumber")
                        .IsUnique();

                    b.ToTable("Spots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = true,
                            SpotNumber = "A-01"
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            SpotNumber = "A-02"
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            SpotNumber = "A-03"
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            SpotNumber = "A-04"
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            SpotNumber = "A-05"
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            SpotNumber = "A-06"
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            SpotNumber = "A-07"
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            SpotNumber = "A-08"
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            SpotNumber = "A-09"
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            SpotNumber = "A-10"
                        },
                        new
                        {
                            Id = 11,
                            IsOccupied = false,
                            SpotNumber = "B-01"
                        },
                        new
                        {
                            Id = 12,
                            IsOccupied = false,
                            SpotNumber = "B-02"
                        },
                        new
                        {
                            Id = 13,
                            IsOccupied = false,
                            SpotNumber = "B-03"
                        },
                        new
                        {
                            Id = 14,
                            IsOccupied = false,
                            SpotNumber = "B-04"
                        },
                        new
                        {
                            Id = 15,
                            IsOccupied = false,
                            SpotNumber = "B-05"
                        },
                        new
                        {
                            Id = 16,
                            IsOccupied = false,
                            SpotNumber = "B-06"
                        },
                        new
                        {
                            Id = 17,
                            IsOccupied = false,
                            SpotNumber = "B-07"
                        },
                        new
                        {
                            Id = 18,
                            IsOccupied = false,
                            SpotNumber = "B-08"
                        },
                        new
                        {
                            Id = 19,
                            IsOccupied = false,
                            SpotNumber = "B-09"
                        },
                        new
                        {
                            Id = 20,
                            IsOccupied = false,
                            SpotNumber = "B-10"
                        },
                        new
                        {
                            Id = 21,
                            IsOccupied = false,
                            SpotNumber = "C-01"
                        },
                        new
                        {
                            Id = 22,
                            IsOccupied = false,
                            SpotNumber = "C-02"
                        },
                        new
                        {
                            Id = 23,
                            IsOccupied = false,
                            SpotNumber = "C-03"
                        },
                        new
                        {
                            Id = 24,
                            IsOccupied = false,
                            SpotNumber = "C-04"
                        },
                        new
                        {
                            Id = 25,
                            IsOccupied = false,
                            SpotNumber = "C-05"
                        },
                        new
                        {
                            Id = 26,
                            IsOccupied = false,
                            SpotNumber = "C-06"
                        },
                        new
                        {
                            Id = 27,
                            IsOccupied = false,
                            SpotNumber = "C-07"
                        },
                        new
                        {
                            Id = 28,
                            IsOccupied = false,
                            SpotNumber = "C-08"
                        },
                        new
                        {
                            Id = 29,
                            IsOccupied = false,
                            SpotNumber = "C-09"
                        },
                        new
                        {
                            Id = 30,
                            IsOccupied = false,
                            SpotNumber = "C-10"
                        },
                        new
                        {
                            Id = 31,
                            IsOccupied = false,
                            SpotNumber = "D-01"
                        },
                        new
                        {
                            Id = 32,
                            IsOccupied = false,
                            SpotNumber = "D-02"
                        },
                        new
                        {
                            Id = 33,
                            IsOccupied = false,
                            SpotNumber = "D-03"
                        },
                        new
                        {
                            Id = 34,
                            IsOccupied = false,
                            SpotNumber = "D-04"
                        },
                        new
                        {
                            Id = 35,
                            IsOccupied = false,
                            SpotNumber = "D-05"
                        },
                        new
                        {
                            Id = 36,
                            IsOccupied = false,
                            SpotNumber = "D-06"
                        },
                        new
                        {
                            Id = 37,
                            IsOccupied = false,
                            SpotNumber = "D-07"
                        },
                        new
                        {
                            Id = 38,
                            IsOccupied = false,
                            SpotNumber = "D-08"
                        },
                        new
                        {
                            Id = 39,
                            IsOccupied = false,
                            SpotNumber = "D-09"
                        },
                        new
                        {
                            Id = 40,
                            IsOccupied = false,
                            SpotNumber = "D-10"
                        });
                });

            modelBuilder.Entity("Domain.Settings.Sitting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("Sittings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("Domain.Entities.Abstracts.Person");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasBaseType("Domain.Entities.Abstracts.Person");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Session", "Session")
                        .WithOne("Payment")
                        .HasForeignKey("Domain.Entities.Payment", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.HasOne("Domain.Entities.Car", "Car")
                        .WithMany("Sessions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "CreatedUser")
                        .WithMany("Sessions")
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Spot", "Spot")
                        .WithMany("Sessions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.DateTimeSlot", "DateTimeSlot", b1 =>
                        {
                            b1.Property<int>("SessionId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EntryTimestamp")
                                .HasColumnType("datetime2")
                                .HasColumnName("EntryTimestamp");

                            b1.Property<DateTime?>("ExitTimestamp")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExitTimestamp");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Car");

                    b.Navigation("CreatedUser");

                    b.Navigation("DateTimeSlot")
                        .IsRequired();

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Spot", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
